import { AlertProvider } from "@/components/ui/showAlert";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Collentra",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <AlertProvider>{children}</AlertProvider>;
}
